### ISSUE TITLE
sciter-x-api.h Has changed

### ISSUE THREAD

**Issue by xizhengchao** [ramon-mendes/SciterSharp#7]
LPVOID reserved1;
  LPVOID reserved2;
  LPVOID reserved3;
  LPVOID reserved4;

  UINT64 SCFN(SciterAtomValue)(const char* name); //
  BOOL   SCFN(SciterAtomNameCB)(UINT64 atomv, LPCSTR_RECEIVER* rcv, LPVOID rcv_param);
  BOOL   SCFN(SciterSetGlobalAsset)(som_asset_t* pass);

The API header file has changed

**Comment by ramon-mendes** [comment]
Thanks! I will take a look at it this weak

**Comment by ramon-mendes** [comment]
Version 3.0.0 is up with the update!
